<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findWithFormations() {
        
        $query = $this->getEntityManager()
        ->createQuery(
            'SELECT c, s, f 
            FROM AppBundle:Category c
            JOIN c.sons s
            JOIN s.formations f
            WHERE c.parent IS NULL'
        );
        return $query->getResult();
   
    }
}
