<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormationRepository extends EntityRepository
{
    
    public function findWhithoutTeacher($id)
    {
       $query = $this->getEntityManager()
        ->createQuery(
            'SELECT f
            FROM AppBundle:Formation f
            LEFT OUTER JOIN f.teachers t 
            WHERE ( t.id IS NULL OR t.id <> :id)'
        )->setParameter('id', $id);

            
        return $query->getResult();
   }
}
