<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentRepository extends EntityRepository
{
    public function findNotInEvent($id)
    {
       $query = $this->getEntityManager()
        ->createQuery(
            'SELECT s
            FROM AppBundle:Student s
            JOIN s.events e
            WHERE e.id <> :id'
        )->setParameter('id', $id);

        return $query->getResult();
   }
}
